### ISSUE TITLE
Command activate failed

### ISSUE THREAD

**Issue by gyopiazza** [MobiusHorizons/dw-utils#19]
Hello and thanks for this tool, it works great plus it's very fast. I'm just having a problem with the `activate'` command which results in:

`Activating version 'myversion' ...  failed`

Any ideas of what it could be?
Thank you

**Comment by MobiusHorizons** [comment]
This got broken with the 17.4 release I believe because they added CSRF validation to business manager pages. There Is a whitelist that may work, but I haven't tested it.

**Comment by danechitoaie** [comment]
Yes, if this tool has a user agent that can be whitelisted and it will work.

PS: I use this tool just for watch & code sync and it's really good. Best one that I've used so far.

**Comment by MobiusHorizons** [comment]
@danechitoaie If I just provide a unique user agent, something like `dw-utils`, are you saying it could be whitelisted? if so, i can probably make that change easily enough.

**Comment by danechitoaie** [comment]
@MobiusHorizons Yes. I also have developed a plugin for Jenkins https://plugins.jenkins.io/osf-builder-suite-for-sfcc-deploy that handles code deployment to staging/CI and that's what I did and can confirm it works.
If you add a user agent, that it's always the same, then it can be whitelisted in BM and it will work.

**Comment by MobiusHorizons** [comment]
@danechitoaie, thanks for the tip. I'll hopefully add this feature this weekend.

**Comment by MobiusHorizons** [comment]
@danechitoaie, @gyopiazza, Fixed in version `1.3.100` The User agent is `dw-utils`
