### ISSUE TITLE
Error when running init on node v8.7.0

### ISSUE THREAD

**Issue by danechitoaie** [MobiusHorizons/dw-utils#23]
I'm getting the following error when running dw-utils init on node v8.7.0
This happens at the last step, after I set `Cartridge Path: (cartridges) cartridges` and press enter.

```
Cartridge Path: (cartridges) cartridges
(node:8493) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Path must be a string. Received null
(node:8493) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by MobiusHorizons** [comment]
Thanks, I will look into it.

**Comment by danechitoaie** [comment]
Same error when I run `dw-utils log error`

**Comment by MobiusHorizons** [comment]
37589ee404b1e07326ad9413c8e80a59efc57157 (version 1.3.133) should fix the promise errors in `watch` `clean` and `upload` I still have to look through `log`

**Comment by MobiusHorizons** [comment]
f9a8809aecada37d87c993fafbd7f1d57fab17ac (version 1.3.134) fixes the promise errors in `log`
