### ISSUE TITLE
Does the upload work on Staging instances?

### ISSUE THREAD

**Issue by gyopiazza** [MobiusHorizons/dw-utils#27]
As per title, I'm not sure if dw-utils supports uploading cartridges on Staging instances. If so, is there any special configuration required? (like certificates etc)

Thank you!

**Comment by MobiusHorizons** [comment]
No `dw-utils` only deals with webdav instances. Uploading to staging instances requires `sftp` (if I understand correctly) with certificate support. I would be very happy to accept a pull request for this functionality, but I won't be building it myself.
